version: '3.4'
services:
  broker1: &kafka
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - 9093:9092
    environment: &env_kafka
      KAFKA_ZOOKEEPER_CONNECT: 10.10.108.110:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.108.110:9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  broker2:
    <<: *kafka
    ports:
      - 9094:9092
    environment:
      <<: *env_kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.32:9094

  broker3:
    <<: *kafka
    ports:
      - 9094:9092
    environment:
      <<: *env_kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.32:9095
